[project]
name = "hashlock-lending"
description = "A trustless lending protocol using sBTC hashlocks."
authors = ["investorphem <dracuul54@gmail.com>"]
telemetry = true
costs_version = 2

[contracts.vault-trait]
path = "contracts/vault-trait.clar"
clarity_version = 2
epoch = "2.1"

[contracts.safe-vault-base]
path = "contracts/safe-vault-base.clar"
clarity_version = 2
epoch = "2.1"

[contracts.sbtc-token]
path = "contracts/sbtc-token.clar"
address = "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4"
clarity_version = 2
epoch = "2.1"

[contracts.hashlock-isolated-sbtc-v1]
path = "contracts/hashlock-isolated-sbtc-v1.clar"
depends_on = ["sbtc-token"]
clarity_version = 2
epoch = "2.1"

[contracts.hashlock-core]
path = "contracts/hashlock-core.clar"
depends_on = ["vault-trait", "hashlock-isolated-sbtc-v1", "safe-vault-base", "sbtc-token"]
clarity_version = 2
epoch = "2.1"