# ==========================================
# HASHLOCK LENDING: MAINNET CONFIGURATION
# ==========================================

[network]
name = "mainnet"
node_rpc_url = "https://api.hiro.so" 

[accounts.deployer]
mnemonic = "clog slab assault art include verb tornado luxury banner include stable angle"
balance = 100_000_000_000

[accounts.wallet_1]
mnemonic = "clog slab assault art include verb tornado luxury banner include stable angle"